//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dcupon.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdminProfile
    {
        public int id { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string PasswordVerificationToken { get; set; }
        public System.DateTime PasswordVerificationTokenExpirydate { get; set; }
        public int Role { get; set; }
        public int IsActive { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public System.DateTime ModifiedOn { get; set; }
    }
}
