//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dcupon.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Api_Import_Status
    {
        public long Id { get; set; }
        public System.DateTime Date { get; set; }
        public string api_Name { get; set; }
        public string api_import_status1 { get; set; }
        public int no_of_row { get; set; }
    }
}
