//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dcupon.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Slider
    {
        public int id { get; set; }
        public int imageid { get; set; }
        public string description { get; set; }
        public string redirectlink { get; set; }
        public int IsActive { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public System.DateTime ModifiedOn { get; set; }
    }
}
