//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dcupon.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Audit
    {
        public int ID { get; set; }
        public int ModuleId { get; set; }
        public string Details { get; set; }
        public System.DateTime CreatedOn { get; set; }
    }
}
